version : '3.8'

services:
  backend:
    build: .
    container_name: facefind_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app  
      - /tmp/facefind:/tmp/facefind
    depends_on:
      - redis
    
  redis:
    image: redis:7-alpine
    container_name: facefind_redis
    ports:
      - "6379:6379"
    restart: always

  worker:
    build : .
    container_name : facefind_worker
    command: celery -A app.core.celery_app worker --loglevel=info
    env_file:
      - .env
    volumes:
       #worker needs access to same tmp folder as backend
      - .:/app
      - /tmp/facefind:/tmp/facefind
    depends_on:
      - redis 








































